server:
  port: ${APP_SERVER_PORT} # Порт, на якому працює сервіс

app:
  link: ${VERIFICATION_APP_LINK}
  notification-link: ${NOTIFICATION_LINK}

logging:
  level:
    com.furniture.authentication_service.filter: DEBUG

spring:
  application:
    name: authentication-service # Назва сервісу
  data:
    jdbc:
      dialect: postgresql
  datasource:
    url: ${SPRING_DATASOURCE_URL} # Підключення до контейнера PostgreSQL
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver # JDBC драйвер
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true # Відображати SQL-запити у логах
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true # Форматувати SQL у логах
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

jwt:
  secret: ${SECRET}  # Секретний ключ для підпису токенів
  accessToken:
    expirationMs: 3600000 # Час життя Access Token (у мілісекундах)
  refreshToken:
    expirationMs: 36000000 # Час життя Refresh Token (у мілісекундах)
  issuer: auth-service

management:
  endpoints:
    web:
      exposure:
        include: "*"
