spring.application.name=product-catalog-service
server.servlet.context-path=/api/v1

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${database_url}
spring.datasource.username=${database_username}
spring.datasource.password=${database_password}
spring.flyway.driver-class-name=org.postgresql.Driver
spring.flyway.url=${database_url}
spring.flyway.user=${database_username}
spring.flyway.password=${database_password}
spring.h2.console.enabled=false
springdoc.api-docs.enabled=false
spring.jpa.hibernate.ddl-auto=validate