# Порт Spring Boot
server.port=${SERVER_PORT}

# Данные подключения к БД PostgreSQL Neon
spring.datasource.url=jdbc:postgresql://ep-floral-glade-a2trwbfy-pooler.eu-central-1.aws.neon.tech/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=ТВОЙ_ПАРОЛЬ
spring.datasource.driver-class-name=org.postgresql.Driver

# HikariCP
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=1800000

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# dialect можно не указывать, Hibernate определит автоматически
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Валидация
spring.jpa.properties.javax.persistence.validation.mode=auto

# Логи SQL
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE