# ===============================
# SERVER
# ===============================
server.port=${PORT:0}

# ===============================
# DATABASE
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Hibernate сам определяет dialect
# НЕ УКАЗЫВАЕМ dialect вручную

# ===============================
# SWAGGER
# ===============================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# health
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always