version: '3.8'

services:
  db:
    image: postgres:15
    container_name: auth-service-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10

  authentication-service:
    container_name: authentication-service
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      APP_SERVER_PORT: ${APP_SERVER_PORT}
      SECRET: ${SECRET}
      VERIFICATION_APP_LINK: ${VERIFICATION_APP_LINK}
      NOTIFICATION_LINK: ${NOTIFICATION_LINK}
    ports:
      - "${APP_SERVER_PORT}:${APP_SERVER_PORT}"

volumes:
  pgdata: