CREATE TABLE category
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_category PRIMARY KEY (id)
);

CREATE TABLE image
(
    id    BIGINT NOT NULL,
    type  VARCHAR(255),
    image OID,
    CONSTRAINT pk_image PRIMARY KEY (id)
);

CREATE TABLE product
(
    id          BIGINT NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    price       FLOAT,
    category_id BIGINT,
    CONSTRAINT pk_product PRIMARY KEY (id)
);

CREATE TABLE product_images
(
    product_id BIGINT NOT NULL,
    images_id  BIGINT NOT NULL
);

ALTER TABLE product_images
    ADD CONSTRAINT uc_product_images_images UNIQUE (images_id);

ALTER TABLE product
    ADD CONSTRAINT FK_PRODUCT_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES category (id);

ALTER TABLE product_images
    ADD CONSTRAINT fk_proima_on_image FOREIGN KEY (images_id) REFERENCES image (id);

ALTER TABLE product_images
    ADD CONSTRAINT fk_proima_on_product FOREIGN KEY (product_id) REFERENCES product (id);