spring.application.name=order_management
# Если переменная не задана, по умолчанию 564
server.port=${SERVER_PORT:564}

# Настройки БД (поддерживают и Docker, и локалку через переменные)
spring.datasource.url=${POSTGRES_URL:jdbc:postgresql://localhost:5432/order-management-db}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
spring.jpa.show-sql=true

# Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
# Это важно, чтобы Swagger не блокировался
springdoc.swagger-ui.enabled=true