name: Keep Services Alive
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  ping-services:
    runs-on: ubuntu-latest
    steps:
      - name: Wake up services
        run: |
          echo "Sending pings to Render services..."
          
          urls=(
            "https://online-store-562team.onrender.com/products?page=0&size=1"
            "https://online-store-562team-zezi.onrender.com/api/carts/1"
            "https://order-management-service-vi3s.onrender.com/orders?page=0&pageSize=1"
            "https://authentication-service-591y.onrender.com/actuator/health/liveness"
          )
          for url in "${urls[@]}"; do
            echo "Pinging $url..."
            curl -s -o /dev/null -w "%{http_code}" "$url" || echo "Failed to ping $url"
            echo -e "\n"
          done
